### ISSUE TITLE
Using timeout option?

### ISSUE THREAD

**Issue by kirkins** [Sekhmet/lightrpc#6]
You'll probably see this on the busy issue tracker but I'm having trouble using the options on this. Not sure if I'm doing it wrong or a bug.

https://github.com/busyorg/busy/pull/1621/files

```
const options = {
  timeout: 15000,
};

const steemUrl = process.env.STEEMJS_URL || 'https://api.steemit.com';

const client = createClient(steemUrl, options);
```

Result:

![screenshot from 2018-03-08 19-05-00](https://user-images.githubusercontent.com/9503662/37183853-192c5912-2306-11e8-9214-1011b620cfb0.png)

![screenshot from 2018-03-08 19-05-05](https://user-images.githubusercontent.com/9503662/37183857-24d2da8e-2306-11e8-95b8-8a99caac6990.png)

**Comment by Sekhmet** [comment]
What is the problem there?

**Comment by kirkins** [comment]
@Sekhmet if you look at the first image it says it should take no longer than 5000ms.

I'm expecting it to say 15000ms since I've passed that in as the timeout option.

**Comment by Sekhmet** [comment]
I don't think that there is a bug in lightrpc.
As I see in Busy PR you seem to update timeout on the server, but test on the client, so this is why it seems not to change.
