### ISSUE TITLE
Handle batch requests

### ISSUE THREAD

**Issue by bonustrack** [Sekhmet/lightrpc#7]
With jussi (api.steemit.com) it's possible to send batch requests. LightRPC should allow this aswell. It would be easier for replay blockchain or could be used in Busy to reduce the number of requests. Instead of sending one operation per request, we can send one array of multiple operation per request.

**Comment by Sekhmet** [comment]
Possible implementation.
1. Change `send` to accept a `request` object with keys `message` and `params`.
2. Add `sendBatch` to accept an array of objects (with the same structure as in 1.)
3. `send` is just wrapper for `sendBatch`. We wrap `request` in the array and call `sendBatch`.

**Comment by Sekhmet** [comment]
It has been implemented at 1.0.0-beta.2.
